export const navigationItems = [
  { label: 'Dashboard', href: '/dashboard' },
  { label: 'Courses', href: '/courses' },
  { label: 'AI Learning', href: '/learning' },
  { label: 'AI Assistant', href: '/ai-assistant' },
  { label: 'Resume Builder', href: '/resume-builder' },
  { label: 'Hackathons', href: '/hackathons' },
  { label: 'Roadmaps', href: '/roadmaps' },
  { label: 'Practice', href: '/practice' },
  { label: 'Jobs', href: '/jobs' },
];

export const features = [
  {
    id: 1,
    title: 'Structured Courses',
    description: 'Learn from industry experts with curated courses tailored to your career path',
    icon: 'BookOpen',
    color: 'from-blue-400 to-cyan-400',
  },
  {
    id: 2,
    title: 'AI-Powered Assistant',
    description: 'Get personalized guidance and instant answers from our advanced AI assistant',
    icon: 'Brain',
    color: 'from-violet-400 to-blue-400',
  },
  {
    id: 3,
    title: 'Resume Builder',
    description: 'Create a stunning, ATS-optimized resume that gets you noticed by recruiters',
    icon: 'FileText',
    color: 'from-cyan-400 to-green-400',
  },
  {
    id: 4,
    title: 'Skill Assessment',
    description: 'Evaluate your technical skills with our comprehensive coding challenges',
    icon: 'Zap',
    color: 'from-orange-400 to-red-400',
  },
  {
    id: 5,
    title: 'Career Roadmaps',
    description: 'Personalized learning paths for different engineering specializations',
    icon: 'Map',
    color: 'from-pink-400 to-violet-400',
  },
  {
    id: 6,
    title: 'Mock Interviews',
    description: 'Practice with AI-powered mock interviews from top tech companies',
    icon: 'Users',
    color: 'from-green-400 to-blue-400',
  },
];

export const engineeringBranches = [
  {
    id: 1,
    title: 'Frontend Engineering',
    description: 'Master React, Vue, Angular and modern web technologies',
    courses: 24,
    difficulty: 'Intermediate',
    duration: '12 weeks',
    icon: 'Code2',
  },
  {
    id: 2,
    title: 'Backend Engineering',
    description: 'Build scalable systems with Node.js, Python, and Go',
    courses: 28,
    difficulty: 'Advanced',
    duration: '14 weeks',
    icon: 'Server',
  },
  {
    id: 3,
    title: 'Full Stack Development',
    description: 'Become a full-stack engineer with comprehensive coverage',
    courses: 36,
    difficulty: 'Advanced',
    duration: '18 weeks',
    icon: 'Layers',
  },
  {
    id: 4,
    title: 'DevOps & Cloud',
    description: 'Master AWS, Docker, Kubernetes and cloud infrastructure',
    courses: 20,
    difficulty: 'Advanced',
    duration: '10 weeks',
    icon: 'Cloud',
  },
  {
    id: 5,
    title: 'Data Engineering',
    description: 'Learn to build data pipelines and analytics platforms',
    courses: 22,
    difficulty: 'Advanced',
    duration: '12 weeks',
    icon: 'Database',
  },
  {
    id: 6,
    title: 'Machine Learning',
    description: 'Deep dive into ML models, neural networks, and AI',
    courses: 25,
    difficulty: 'Advanced',
    duration: '14 weeks',
    icon: 'Cpu',
  },
];

export const pricingPlans = [
  {
    id: 1,
    name: 'Starter',
    price: '29',
    description: 'Perfect for beginners exploring tech careers',
    features: [
      'Access to 50+ courses',
      'Basic AI Assistant (5 conversations/day)',
      'Resume template access',
      'Community forums',
      'Email support',
    ],
    highlighted: false,
  },
  {
    id: 2,
    name: 'Professional',
    price: '79',
    description: 'For serious developers committed to growth',
    features: [
      'Access to 200+ courses',
      'Unlimited AI Assistant',
      'Advanced Resume Builder',
      'Mock interview practice',
      'Personalized roadmaps',
      'Priority support',
      'Skill assessments',
      'Certificate programs',
    ],
    highlighted: true,
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Alex Johnson',
    role: 'Senior Software Engineer at Google',
    content: 'This platform completely transformed my career. The courses are world-class and the AI assistant is incredibly helpful.',
    avatar: '👨‍💼',
  },
  {
    id: 2,
    name: 'Sarah Chen',
    role: 'Full Stack Developer at Meta',
    content: 'The resume builder got me interviews at every top company I applied to. Highly recommend!',
    avatar: '👩‍💼',
  },
  {
    id: 3,
    name: 'Marcus Williams',
    role: 'DevOps Engineer at Amazon',
    content: 'The career roadmaps are incredibly detailed and practical. This is exactly what I needed to level up.',
    avatar: '👨‍💼',
  },
];

export const dashboardSections = [
  {
    id: 1,
    title: 'Continue Learning',
    description: 'Resume your current courses and progress',
  },
  {
    id: 2,
    title: 'Skill Assessment',
    description: 'Track your technical skills and growth',
  },
  {
    id: 3,
    title: 'Hackathons',
    description: 'Upcoming and past hackathon opportunities',
  },
];

export const sampleCourses = [
  {
    id: 1,
    title: 'Advanced React Architecture',
    instructor: 'Dan Abramov',
    level: 'Advanced',
    duration: '8 weeks',
    progress: 0,
    rating: 4.8,
    reviews: 1240,
    image: 'React',
    description: 'Master advanced React patterns, rendering performance, and large-scale application architecture.'
  },
  {
    id: 2,
    title: 'Distributed Systems & Microservices',
    instructor: 'Alex Xu',
    level: 'Advanced',
    duration: '10 weeks',
    progress: 0,
    rating: 4.9,
    reviews: 890,
    image: 'Architecture',
    description: 'Learn to design, build and scale distributed systems using modern microservices patterns.'
  },
  {
    id: 3,
    title: 'Full-Stack TypeScript Mastery',
    instructor: 'Matt Pocock',
    level: 'Intermediate',
    duration: '6 weeks',
    progress: 0,
    rating: 4.7,
    reviews: 2100,
    image: 'TypeScript',
    description: 'The ultimate guide to type-safe development across the entire stack using TypeScript.'
  },
  {
    id: 4,
    title: 'Cloud Native AWS Architect',
    instructor: 'Stephane Maarek',
    level: 'Advanced',
    duration: '12 weeks',
    progress: 0,
    rating: 4.8,
    reviews: 1560,
    image: 'AWS',
    description: 'Comprehensive preparation for AWS Solutions Architect certification with real-world labs.'
  },
  {
    id: 5,
    title: 'Modern Backend with Go & Kubernetes',
    instructor: 'Kelsey Hightower',
    level: 'Advanced',
    duration: '9 weeks',
    progress: 0,
    rating: 4.9,
    reviews: 750,
    image: 'Go',
    description: 'Build high-performance concurrent backends and deploy them on Kubernetes clusters.'
  },
  {
    id: 6,
    title: 'Data Structures & Algorithms for Interviews',
    instructor: 'Gayle Laakmann McDowell',
    level: 'Intermediate',
    duration: '8 weeks',
    progress: 0,
    rating: 4.9,
    reviews: 3200,
    image: 'Algorithms',
    description: 'Master the technical interview with deep dives into complex algorithms and data structures.'
  },
  {
    id: 7,
    title: 'DevOps & CI/CD Pipeline Engineering',
    instructor: 'Brendan Burns',
    level: 'Advanced',
    duration: '7 weeks',
    progress: 0,
    rating: 4.7,
    reviews: 640,
    image: 'DevOps',
    description: 'Learn to automate everything from code commit to production deployment.'
  },
  {
    id: 8,
    title: 'AI/ML for Software Engineers',
    instructor: 'Andrew Ng',
    level: 'Beginner',
    duration: '14 weeks',
    progress: 0,
    rating: 4.9,
    reviews: 4500,
    image: 'AI',
    description: 'Practical machine learning for engineers looking to integrate AI into their applications.'
  },
  {
    id: 9,
    title: 'System Design Interview Masterclass',
    instructor: 'Alex Xu',
    level: 'Advanced',
    duration: '6 weeks',
    progress: 0,
    rating: 4.9,
    reviews: 5100,
    image: 'SystemDesign',
    description: 'Design scalable systems like Netflix, Uber, and Twitter. Ace any system design interview.'
  },
  {
    id: 10,
    title: 'Next.js 14 Full Stack Development',
    instructor: 'Lee Robinson',
    level: 'Intermediate',
    duration: '5 weeks',
    progress: 0,
    rating: 4.8,
    reviews: 2800,
    image: 'NextJS',
    description: 'Build production-ready full-stack apps with Next.js App Router, Server Actions, and more.'
  },
  {
    id: 11,
    title: 'Docker & Kubernetes in Production',
    instructor: 'Bret Fisher',
    level: 'Intermediate',
    duration: '8 weeks',
    progress: 0,
    rating: 4.7,
    reviews: 1900,
    image: 'Docker',
    description: 'Containerize applications and orchestrate them at scale with Docker Swarm and Kubernetes.'
  },
  {
    id: 12,
    title: 'Python for Data Science & ML',
    instructor: 'Jose Portilla',
    level: 'Beginner',
    duration: '10 weeks',
    progress: 0,
    rating: 4.8,
    reviews: 6200,
    image: 'Python',
    description: 'From Python basics to Pandas, NumPy, Scikit-learn, and building real ML models.'
  },
  {
    id: 13,
    title: 'GraphQL API Design',
    instructor: 'Eve Porcello',
    level: 'Intermediate',
    duration: '4 weeks',
    progress: 0,
    rating: 4.6,
    reviews: 980,
    image: 'GraphQL',
    description: 'Design and build efficient, type-safe APIs with GraphQL, Apollo Server, and subscriptions.'
  },
  {
    id: 14,
    title: 'Rust for Systems Programming',
    instructor: 'Jon Gjengset',
    level: 'Advanced',
    duration: '12 weeks',
    progress: 0,
    rating: 4.9,
    reviews: 720,
    image: 'Rust',
    description: 'Write blazing-fast, memory-safe systems software with Rust. From ownership to async.'
  },
  {
    id: 15,
    title: 'Cybersecurity Fundamentals',
    instructor: 'Troy Hunt',
    level: 'Beginner',
    duration: '6 weeks',
    progress: 0,
    rating: 4.7,
    reviews: 3100,
    image: 'Security',
    description: 'Learn ethical hacking, OWASP Top 10, penetration testing, and secure coding practices.'
  },
  {
    id: 16,
    title: 'PostgreSQL & Database Engineering',
    instructor: 'Hussein Nasser',
    level: 'Intermediate',
    duration: '7 weeks',
    progress: 0,
    rating: 4.8,
    reviews: 1450,
    image: 'Database',
    description: 'Deep dive into PostgreSQL internals, indexing strategies, query optimization, and scaling.'
  },
];

export type HackathonStatus = 'upcoming' | 'ongoing' | 'past';
export type HackathonPlatform = 'unstop' | 'hack2skill' | 'devfolio' | 'other';

export interface Hackathon {
  id: number;
  title: string;
  organizer: string;
  date: string;
  location: string;
  prize: string;
  participants: number;
  status: HackathonStatus;
  platform: HackathonPlatform;
  url: string;
  tags: string[];
  domain: string;
  teamSize: string;
  description: string;
}

export const hackathons: Hackathon[] = [
  // --- UNSTOP ---
  {
    id: 1,
    title: 'Smart India Hackathon 2025',
    organizer: 'Ministry of Education, Govt. of India',
    date: 'Aug 20–22, 2025',
    location: 'Pan India (Offline + Virtual)',
    prize: '₹1,00,000',
    participants: 50000,
    status: 'upcoming',
    platform: 'unstop',
    url: 'https://unstop.com/hackathons/smart-india-hackathon',
    tags: ['AI', 'GovTech', 'Open Innovation', 'Hardware'],
    domain: 'Open Innovation',
    teamSize: '2–6',
    description: 'India\'s biggest national hackathon where students solve real government problem statements across 6 domains.',
  },
  {
    id: 2,
    title: 'HackWithInfy 2025',
    organizer: 'Infosys',
    date: 'Jul 10–12, 2025',
    location: 'Virtual',
    prize: '₹5,00,000',
    participants: 30000,
    status: 'upcoming',
    platform: 'unstop',
    url: 'https://unstop.com/hackathons/hackwithinfy',
    tags: ['Full Stack', 'Cloud', 'Enterprise', 'Java'],
    domain: 'Software Development',
    teamSize: '1–3',
    description: 'Infosys\'s flagship coding competition for engineering students to solve enterprise-grade challenges.',
  },
  {
    id: 3,
    title: 'Flipkart Grid 6.0',
    organizer: 'Flipkart',
    date: 'Jun 15 – Sep 30, 2025',
    location: 'Virtual + Bengaluru Finals',
    prize: '₹3,00,000',
    participants: 25000,
    status: 'upcoming',
    platform: 'unstop',
    url: 'https://unstop.com/hackathons/flipkart-grid-6',
    tags: ['E-Commerce', 'ML', 'Backend', 'Supply Chain'],
    domain: 'E-Commerce & Retail Tech',
    teamSize: '2–3',
    description: 'Flipkart\'s engineering challenge testing skills in software engineering, ML, and supply chain optimization.',
  },
  {
    id: 4,
    title: 'Tata Imagination Challenge 2025',
    organizer: 'Tata Group',
    date: 'Sep 1–30, 2025',
    location: 'Virtual',
    prize: '₹2,00,000 + PPO',
    participants: 20000,
    status: 'upcoming',
    platform: 'unstop',
    url: 'https://unstop.com/hackathons/tata-imagination-challenge',
    tags: ['Sustainability', 'IoT', 'AI', 'Social Impact'],
    domain: 'Sustainability & Innovation',
    teamSize: '2–4',
    description: 'Tata Group\'s innovation challenge for students to build solutions addressing real-world sustainability problems.',
  },
  {
    id: 5,
    title: 'Myntra HackerRamp 2025',
    organizer: 'Myntra',
    date: 'Jul 1 – Aug 15, 2025',
    location: 'Virtual + Bengaluru',
    prize: '₹2,50,000',
    participants: 15000,
    status: 'upcoming',
    platform: 'unstop',
    url: 'https://unstop.com/hackathons/myntra-hackerramp',
    tags: ['Fashion Tech', 'ML', 'Recommendation', 'UI/UX'],
    domain: 'Fashion & Retail Tech',
    teamSize: '2–3',
    description: 'Build the future of fashion tech — from personalized recommendations to AR try-ons and trend forecasting.',
  },
  {
    id: 6,
    title: 'Walmart Sparkathon 2025',
    organizer: 'Walmart Global Tech India',
    date: 'Aug 5–25, 2025',
    location: 'Virtual',
    prize: '₹3,00,000 + Internship',
    participants: 18000,
    status: 'upcoming',
    platform: 'unstop',
    url: 'https://unstop.com/hackathons/walmart-sparkathon',
    tags: ['Retail Tech', 'Cloud', 'Data Engineering', 'AI'],
    domain: 'Retail & Supply Chain',
    teamSize: '2–4',
    description: 'Walmart\'s tech challenge for students to innovate in retail, supply chain, and customer experience.',
  },
  {
    id: 7,
    title: 'HackRx 5.0 by Bajaj Finserv',
    organizer: 'Bajaj Finserv Health',
    date: 'Sep 10–12, 2025',
    location: 'Virtual',
    prize: '₹5,00,000',
    participants: 12000,
    status: 'upcoming',
    platform: 'unstop',
    url: 'https://unstop.com/hackathons/hackrx-5',
    tags: ['HealthTech', 'AI', 'NLP', 'FinTech'],
    domain: 'HealthTech & FinTech',
    teamSize: '2–4',
    description: 'Build AI-powered solutions for healthcare and insurance — from claims processing to patient engagement.',
  },
  // --- HACK2SKILL ---
  {
    id: 8,
    title: 'Hack2Skill GenAI Hackathon',
    organizer: 'Hack2Skill',
    date: 'May 25–27, 2025',
    location: 'Virtual',
    prize: '$10,000',
    participants: 8000,
    status: 'upcoming',
    platform: 'hack2skill',
    url: 'https://hack2skill.com/hack/hackathons',
    tags: ['GenAI', 'LLMs', 'RAG', 'Agents'],
    domain: 'Artificial Intelligence',
    teamSize: '1–4',
    description: 'Build production-ready GenAI applications using LLMs, RAG pipelines, and autonomous agents.',
  },
  {
    id: 9,
    title: 'Google Solution Challenge 2025',
    organizer: 'Google Developer Student Clubs',
    date: 'Jan – Apr 2025',
    location: 'Global (Virtual)',
    prize: '$3,000 + Mentorship',
    participants: 100000,
    status: 'ongoing',
    platform: 'hack2skill',
    url: 'https://hack2skill.com/hack/google-solution-challenge',
    tags: ['Google Cloud', 'SDGs', 'Mobile', 'Firebase'],
    domain: 'Social Impact',
    teamSize: '3–4',
    description: 'Build solutions for UN Sustainable Development Goals using Google technologies. Top 100 teams get mentorship.',
  },
  {
    id: 10,
    title: 'Microsoft Imagine Cup 2025',
    organizer: 'Microsoft',
    date: 'Oct 2025',
    location: 'Global (Seattle Finals)',
    prize: '$100,000',
    participants: 60000,
    status: 'upcoming',
    platform: 'hack2skill',
    url: 'https://hack2skill.com/hack/microsoft-imagine-cup',
    tags: ['Azure', 'AI', 'Social Impact', 'Mixed Reality'],
    domain: 'Social Impact',
    teamSize: '1–4',
    description: 'Microsoft\'s global student technology competition. Build AI-powered solutions that make a real-world impact.',
  },
  {
    id: 11,
    title: 'AWS DeepRacer Student League',
    organizer: 'Amazon Web Services',
    date: 'Ongoing 2025',
    location: 'Virtual',
    prize: 'AWS Credits + Swag',
    participants: 40000,
    status: 'ongoing',
    platform: 'hack2skill',
    url: 'https://hack2skill.com/hack/aws-deepracer',
    tags: ['AWS', 'Reinforcement Learning', 'ML', 'Cloud'],
    domain: 'Machine Learning',
    teamSize: '1',
    description: 'Train autonomous racing models using reinforcement learning on AWS and compete on virtual tracks.',
  },
  {
    id: 12,
    title: 'NASSCOM AI Gamechangers 2025',
    organizer: 'NASSCOM',
    date: 'Oct 1–31, 2025',
    location: 'Virtual + Delhi',
    prize: '₹10,00,000',
    participants: 5000,
    status: 'upcoming',
    platform: 'hack2skill',
    url: 'https://hack2skill.com/hack/nasscom-ai-gamechangers',
    tags: ['AI', 'Deep Tech', 'Startup', 'Enterprise AI'],
    domain: 'Artificial Intelligence',
    teamSize: '2–5',
    description: 'NASSCOM\'s premier AI challenge for startups and students building transformative AI solutions for India.',
  },
  // --- DEVFOLIO ---
  {
    id: 13,
    title: 'ETHIndia 2025',
    organizer: 'Devfolio & ETHGlobal',
    date: 'Nov 7–9, 2025',
    location: 'Bengaluru',
    prize: '$500,000 in prizes',
    participants: 3000,
    status: 'upcoming',
    platform: 'devfolio',
    url: 'https://devfolio.co/hackathons',
    tags: ['Web3', 'Ethereum', 'DeFi', 'Smart Contracts'],
    domain: 'Blockchain & Web3',
    teamSize: '2–4',
    description: 'Asia\'s largest Ethereum hackathon. Build the next generation of decentralized applications in Bengaluru.',
  },
  {
    id: 14,
    title: 'HackBout 2025',
    organizer: 'Devfolio Community',
    date: 'Jun 20–22, 2025',
    location: 'Virtual',
    prize: '₹1,50,000',
    participants: 5000,
    status: 'upcoming',
    platform: 'devfolio',
    url: 'https://devfolio.co/hackathons',
    tags: ['Open Source', 'Web Dev', 'Mobile', 'AI'],
    domain: 'Open Innovation',
    teamSize: '2–4',
    description: 'A community-driven hackathon open to all domains — web, mobile, AI, and open source contributions.',
  },
  {
    id: 15,
    title: 'Hack This Fall 2025',
    organizer: 'Hack This Fall',
    date: 'Oct 3–5, 2025',
    location: 'Virtual',
    prize: '$5,000',
    participants: 6000,
    status: 'upcoming',
    platform: 'devfolio',
    url: 'https://devfolio.co/hackathons',
    tags: ['Open Innovation', 'Web3', 'AI', 'Social Good'],
    domain: 'Open Innovation',
    teamSize: '2–4',
    description: 'India\'s most inclusive virtual hackathon welcoming beginners and experts to build for social good.',
  },
  // --- OTHER ---
  {
    id: 16,
    title: 'IIT Bombay Techfest Hackathon',
    organizer: 'IIT Bombay',
    date: 'Dec 19–21, 2025',
    location: 'IIT Bombay, Mumbai',
    prize: '₹2,00,000',
    participants: 10000,
    status: 'upcoming',
    platform: 'other',
    url: 'https://techfest.org/competitions',
    tags: ['Robotics', 'AI', 'Hardware', 'IoT'],
    domain: 'Deep Tech',
    teamSize: '2–4',
    description: 'Asia\'s largest science and technology festival hosts a flagship hackathon across AI, robotics, and hardware.',
  },
  {
    id: 17,
    title: 'CodeChef SnackDown 2025',
    organizer: 'CodeChef',
    date: 'Sep – Nov 2025',
    location: 'Virtual + Bengaluru Finals',
    prize: '₹5,00,000',
    participants: 35000,
    status: 'upcoming',
    platform: 'other',
    url: 'https://www.codechef.com/snackdown',
    tags: ['Competitive Programming', 'Algorithms', 'DSA'],
    domain: 'Competitive Programming',
    teamSize: '2',
    description: 'CodeChef\'s global team programming contest with multiple elimination rounds leading to an offline finale.',
  },
  {
    id: 18,
    title: 'HackCBS 7.0',
    organizer: 'Shaheed Sukhdev College of Business Studies',
    date: 'Oct 18–19, 2025',
    location: 'Delhi University, Delhi',
    prize: '₹1,00,000',
    participants: 2000,
    status: 'upcoming',
    platform: 'devfolio',
    url: 'https://devfolio.co/hackathons',
    tags: ['FinTech', 'EdTech', 'AI', 'Web Dev'],
    domain: 'Open Innovation',
    teamSize: '2–4',
    description: 'One of Delhi\'s biggest student-run hackathons with tracks in FinTech, EdTech, AI, and sustainability.',
  },
  {
    id: 19,
    title: 'Kavach Cybersecurity Hackathon',
    organizer: 'MHA & Bureau of Police Research',
    date: 'Aug 2025',
    location: 'Pan India',
    prize: '₹10,00,000',
    participants: 8000,
    status: 'upcoming',
    platform: 'other',
    url: 'https://kavach.mic.gov.in',
    tags: ['Cybersecurity', 'GovTech', 'Forensics', 'AI'],
    domain: 'Cybersecurity',
    teamSize: '3–6',
    description: 'Government of India\'s national cybersecurity hackathon to build tools for law enforcement and national security.',
  },
  {
    id: 20,
    title: 'Toycathon 2025',
    organizer: 'Ministry of Education & AICTE',
    date: 'Jul – Sep 2025',
    location: 'Pan India',
    prize: '₹50,000',
    participants: 15000,
    status: 'upcoming',
    platform: 'other',
    url: 'https://toycathon.mic.gov.in',
    tags: ['EdTech', 'Gaming', 'AR/VR', 'Innovation'],
    domain: 'EdTech & Gaming',
    teamSize: '2–5',
    description: 'AICTE\'s challenge to design innovative Indian toys and games that are educational, cultural, and tech-driven.',
  },
];
